### ISSUE TITLE
Stop Reminders after 5/1

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#100]
Looks like there are more reminders after 5/1 which is the national college decision date.  We probably shouldn't display those. 
![img_0957](https://cloud.githubusercontent.com/assets/8203279/20216391/42e7fa44-a7e8-11e6-8ef7-a7b816477e88.jpg)

**Comment by bobderrico80** [comment]
I noticed this as well. All of the reminders that occur after the last school's due date are ACT/SAT registration/test dates. 

We could suppress test reminders after 5/1, but maybe a better idea would be to suppress the reminders after the latest school's application due date?

**Comment by michiQ** [comment]
hmmm...I think guidance counselors like to 'finish the loop' if you will by saying - ok, now you have all these acceptances, you have to say yes to somebody and you have to do that by May 1.    Maybe we do suprress reminders after the application due date and then, by default - always include the 5/1 date?

**Comment by michiQ** [comment]
well- a funny thing happened.  I did remove all the test dates and those are not showing up anymore.  but for some reason 7/1/2017 and 10/1/2017 reminders are showing on a 4/1/2017 submission date. Here are screen shots

**Comment by michiQ** [comment]
![img_3664](https://cloud.githubusercontent.com/assets/8203279/21509324/d179efec-cc55-11e6-8d7b-d54e4ce72e6f.jpg)

**Comment by bobderrico80** [comment]
The 10/1/2017 is probably because FAFSA is an absolute date (just like 5/1). It looks like we will still need some logic to handle this. I am not sure about 7/1... that might be a hard date as well (there may be an absolute "Summer" timeframe set to 7/1).

**Comment by bobderrico80** [comment]
I am wondering if this is still an issue. A lot of the noise with the late reminders was related to having all of the ACT/SAT test dates in there. I am going to move this back to "Thinking about it." If in our testing we find that it is an issue, we can move it back up.

**Comment by michiQ** [comment]
I'm still seeing the 7/1/2017 and the 10/1/2017 date.  I'll check and see if its an admin config.

**Comment by bobderrico80** [comment]
See #132 for comments about this.

**Comment by michiQ** [comment]
This is resolved.
