### ISSUE TITLE
Group Think - Do we need another school heading when we group by Date?

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#101]
I put in four schools so some of them have reminders falling on the same day.  When I look at them by date, I can't tell which reminder is for which school.   Like in this screenshot it shows Request Transcripts
![img_0958](https://cloud.githubusercontent.com/assets/8203279/20216473/be2917a6-a7e8-11e6-9bbf-3e5eb0c05df3.jpg)
 twice, but one is for Temple and one is for Camden Community College.

Question for the group:

Something we have to worry about yes/no?
Possible solutions if yes?

(i'm thinking maybe take the school and append it to the front  so it says 'Temple - Request Transcripts'.  But also thinking it will make those headers VERY busy.

**Comment by bobderrico80** [comment]
This is also a bug... it should be combining duplicate reminders into one single reminder (in these cases, the %SCHOOL% variable gets populated with a list of all of the schools that are associated with the reminder). I will take a look at this and see why the expected behavior is not happening.

**Comment by michiQ** [comment]
Wow - that's an elegant solution - very cool!

**Comment by michiQ** [comment]
Linked to #90

**Comment by michiQ** [comment]
closing this as we have other issues to combine schools so a header isn't necessary.
