### ISSUE TITLE
We should get the login page when we click Logout

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#102]
So when we click logout, then the login page should pop up. 

![screen shot 2016-11-11 at 8 11 29 am](https://cloud.githubusercontent.com/assets/8203279/20216495/d74300da-a7e8-11e6-935c-7d39d9c7fed1.png)

**Comment by bobderrico80** [comment]
Hmmm... this should already be happening. I will take a look at why it is not working.
