### ISSUE TITLE
Keyboard pops up when you click on the questions in onboarding

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#106]
When you click on the questions on the application submission date screen, the keyboard pops up.

**Comment by michiQ** [comment]
![img_3505](https://cloud.githubusercontent.com/assets/8203279/20224296/ca67d502-a80b-11e6-8410-459af489aee3.jpg)

**Comment by bobderrico80** [comment]
I will look into this.

**Comment by michiQ** [comment]
no longer an issue.  closing
