### ISSUE TITLE
Prevent Users from using a Backdate Submission date

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#111]

**Comment by michiQ** [comment]
Right now I could enter 2/1/2016 in the application submission date. So that then gives me a very big list of reminders :).  Suggest that we not allow a date earlier than the current date.

**Comment by michiQ** [comment]
I think we probably should do this one if we can.  It was in backlog, but it can be really confusing for the users if they for example, fat finger the year and don't notice it, and then their reminders are skewed and they are following a skewed plan for a while before they notice it.

**Comment by bobderrico80** [comment]
Interesting... there is _some_ min-date logic. Users are not able to use the date picker to pick a date in the past. However, they can still type a date in the past. I will add this check to the form validation so that they cannot submit if they have entered a date in the past.
