### ISSUE TITLE
Create Text Message Field

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#114]
We are thinking that we need a field specifically to put very simple messages in text messages.   For example, instead of sending "Check in with your teachers by 1/1/2017 about the status of CCCPs recommendations." we will say instead 'Check Recommendation Status'

**Comment by michiQ** [comment]
Actually thinking - now that I see the screen shot of the text message in slack - that perhaps we don't have to do this now.  I mean one of the longest titles we have is 'Ask Counselor for Recommendation' and it gets cut off at 'Ask Counselor for Recommenda'.  That's not too bad really and I think maybe we could even think of ways to shorten it.  I' m assuming that in that sceenshot the 'Name' field of the reminder?  If so..I think we should just use that and not have a unique text message field.

**Comment by michiQ** [comment]
<img width="351" alt="screen shot 2016-12-27 at 5 54 47 pm" src="https://cloud.githubusercontent.com/assets/8203279/21510095/986d33dc-cc5d-11e6-9969-b2cad88769ba.png">

**Comment by bobderrico80** [comment]
I've actually got the migrations and code written to do this. In the above examples, the text is being pulled from a new `smsMessage` column on the table. In creating the migration, I am just having it use the first 28 characters of the `name` column to start, and then we can adjust as needed.

**Comment by michiQ** [comment]
oh nice! ok sounds good!
