### ISSUE TITLE
Test like a crazy woman

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#122]

**Comment by michiQ** [comment]
Seems like something is stopping on boarding from moving forward in qam. I'm stuck on this screen. 
 
![image_uploaded_from_ios_480](https://cloud.githubusercontent.com/assets/8203279/22405173/6a28d314-e60c-11e6-9138-bf9899b156ec.jpg)

Clicking the button or swiping aren't moving the app forward.

**Comment by michiQ** [comment]
currently blocked by #157

**Comment by bobderrico80** [comment]
@michiQ  - Are you still blocked on this?
