### ISSUE TITLE
QAM: Click to manage your text messages might need to get smaller and move to the bottom

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#129]

**Comment by michiQ** [comment]
Right after onboarding we have some smaller screens that scroll over with arrows that point to where to manage text messages and where to see reminders.

We may need to either a) push them Up and Down a bit, b) make the font and box smaller or c) come up with a different UX solution.  Not sure which is easier to do and am relying on the team to let me know if I should start working on C or if A or B are possible. 

![file_003](https://cloud.githubusercontent.com/assets/8203279/22508870/e1e33ba2-e859-11e6-999d-157753060db6.jpeg)


![file_004](https://cloud.githubusercontent.com/assets/8203279/22508878/e6a630e0-e859-11e6-9562-55b42b9ae2df.jpeg)



Related to #79

**Comment by bobderrico80** [comment]
Overall I like the idea of what we currently have. Probably some combination of A and B would be sufficient.

**Comment by michiQ** [comment]
Moving this one to the backlog because I think it will be dealt with a new combo modal discussed in #147

**Comment by michiQ** [comment]
closing due to work on 147
