### ISSUE TITLE
Need to think about how to handle ASAP Reminders

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#133]
So the asap reminders show up as a lot when we put in a school that is due in the near future (like for example, 3/1).  What happens is that all the reminders from the past get put in ASAP.  I'm wondering if it would make more sense to group them by the date they were due, even if it was a past date.  This would assume that the user would 'get it' that they were late and that was when stuff was due.  The reason for doing this is that there is a really long list and that there are repeated things in that list and that can be confusing too.  Wondering about your thoughts here.

**Comment by michiQ** [comment]
![file_002 1](https://cloud.githubusercontent.com/assets/8203279/22509610/d9f44a14-e85c-11e6-979e-aaf39cd91d9e.jpeg)

**Comment by michiQ** [comment]
So the asap reminders show up as a lot when we put in a school that is due in the near future (like for example, 3/1). What happens is that all the reminders from the past get put in ASAP. I'm wondering if it would make more sense to group them by the date they were due, even if it was a past date. This would assume that the user would 'get it' that they were late and that was when stuff was due. The reason for doing this is that there is a really long list and that there are repeated things in that list and that can be confusing too. Wondering about your thoughts here.

**Comment by bobderrico80** [comment]
This will be handled by #117. Anything in the ASAP  group is overdue. The current logic has all late reminders displaying there. With the changes suggested by #117, the only ASAP reminders would be ones for which we've provided a late message/detail. This would allow us to tailor what would go into the list, as we would only add late message/details to messages that should appear in ASAP.

**Comment by michiQ** [comment]
handled by #117
