### ISSUE TITLE
Right after adding the first school, let people know that they will start receiving text messages

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#147]

**Comment by michiQ** [comment]
I think we need to let people know, like maybe with a pop up, that they will start receiving text messages on the dates indicated in the school plan.  It's like just the final - great you're fully set up - type message.

**Comment by michiQ** [comment]
Let me know what you think  - I'll do a mock up once I hear what others think.

**Comment by bobderrico80** [comment]
We could add that as a third pop-up bubble after the onboarding process?

**Comment by michiQ** [comment]
yeah - that's what i'm thinking - but also was toying with the idea of an overlay screen?  Something that is slightly transparent, and has directional arrow that would replace the 'click here to manage' pop-ups along with 'great you'll now get messages on the dates indicated in your plan...' message.  Meaning like one screen to handle it all.    what do you all  think?

**Comment by bobderrico80** [comment]
That could work too.  We could use the 'modal' view (the same popup we use for help, error messages, etc.)

**Comment by michiQ** [comment]
Ok folks - what do you think of this? https://preview.uxpin.com/9b4ba59f29ab83a34a5d98f606f4696aab330b21#/pages/31898600

**Comment by bobderrico80** [comment]
Oooh I like that. So it would just be another step of the onboarding. Then we can get rid of the overlays . that happen after the initial onboarding?

**Comment by michiQ** [comment]
Exatamente (not a word - i know)

**Comment by michiQ** [comment]
so basically after watching a few people go through the app they really just needed to know  ' hey there are buttons at the bottom that do stuff.' I usually would have to tell them ' look at the buttons at the bottom.'  They didn't need to know *exactly* what they did, just that the bottom part of the page was where to go do stuff.  They other thing was that people didn't know to actually _click_ on the school.  So that's why the top of the screen says  essentially 'tap on the school' and the bottom part of the screen is basically 'there are buttons that do stuff at the bottom'. just said better.

**Comment by bobderrico80** [comment]
Took the opportunity while working on this to do some further refactoring of the CSS of the onboarding process, and have QAed on several screen sizes/orientations, and found a good balance. More technically, I switched over to using flexboxes, which make it a lot easier to center things vertically, which was the route of many of our problems.

I have this about finished, up, but want to apply the same CSS fixes to the login screen as well (since it has a similar look/feel). My goal is to have this finished up early this week.

**Comment by michiQ** [comment]
LOOKS GREAT!!!! woot!!! Onboarding is looking really really good - the balance is great, makes it Sooooooo easy to onboard - fun even! Awesome job!!!

**Comment by bobderrico** [comment]
I haven't pushed my changes yet :-) It will look even better when I do.
