### ISSUE TITLE
QAM: dot dot dots... can we say goodbye?

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#155]

**Comment by michiQ** [comment]
So the horizontal screen has next and prev buttons in onboading and the vertical has the dot dot dots.  When you go to horizontal you can see both.  I'm all in favor of just removing the dot dot dots and just using the next and prev buttons on both the vertical and horizontal.  whaddya say?

**Comment by michiQ** [comment]
![img_1282](https://cloud.githubusercontent.com/assets/8203279/23589979/c93f16d8-01a5-11e7-94d6-71754582b2fe.jpg)
![img_1281](https://cloud.githubusercontent.com/assets/8203279/23589980/ca76e1ca-01a5-11e7-958e-1fa72e050853.jpg)

**Comment by bobderrico80** [comment]
As mentioned in the slack channel, I am working on a fix for this in #147.

**Comment by michiQ** [comment]
Bye dots!  you will be missed.  hellloooo buttons!
