### ISSUE TITLE
QAM: Persist the Plus Button

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#156]

**Comment by michiQ** [comment]
When I click on a school, the plus button in the bottom right goes away.   It also goes away when you click view by date.  Can we have it stay on the bottom bar?

**Comment by michiQ** [comment]
![img_1283](https://cloud.githubusercontent.com/assets/8203279/23590020/912c42a6-01a6-11e7-864a-a55102843886.jpg)

**Comment by bobderrico80** [comment]
Yes, this can be added in. I believe the original mockups only had the plus button on the school view, but it should be easy to add (I think it is conditionally hidden, currently).
