### ISSUE TITLE
Send text message after onboarding

### ISSUE THREAD

**Issue by bobderrico80** [yadaguru/yadaguru-app#171]
Create endpoint to hit when user completes onboarding.

In response to onboarding, send a welcome sms message, suggesting that users save the number in their address book, and provide brief instructions for turning off messages.

michiQ to craft language and assign back to dev.

**Comment by michiQ** [comment]
text "Welcome to Yadaguru (YG).  You will be receiving texts from me.  If you want to stop receiving messages go to yadaguru.com>view by school>off switch."
