### ISSUE TITLE
QAM: On view by date view, Application Date code doesn't render as the date

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#174]
to reproduce:

1. create a school
2. go to view by date
3. Find the Application Submission Date Reminder
 
You'll see : "Penn's application is due %APPLICATION_DATE%" instead of "Penn's application is due 4/15/2017"

Interestingly, this does not happen on the view by school view where it renders just fine.

**Comment by michiQ** [comment]
![img_0007](https://cloud.githubusercontent.com/assets/8203279/24422932/467997ba-13c9-11e7-864e-44bb219301c9.jpg)

**Comment by bobderrico80** [comment]
bah... I have a feeling this is a regression caused by changes on #157. Taking a look at it now.

**Comment by michiQ** [comment]
Hmmm probably a dumb question but was the code pushed to qam?  Still showing up there. 
![img_1522](https://cloud.githubusercontent.com/assets/8203279/24484637/400dc540-14cd-11e7-8879-98ff2484d0ef.PNG)

**Comment by bobderrico80** [comment]
No, I am still working on a fix. #157 was the deduplication fix. That fix caused this bug. Working on it now.

**Comment by bobderrico80** [comment]
While fixing this, I had a thought. How do we combine due dates for schools when we de-duplicate? Currently, we are only showing one date (the last one). This probably isn't what we want. One thought would be to apply the same logic for joining the dates as we do the schools (for example: 2/1/2018 and 2/7/2018... or 2/1/2018, 2/7/2018, and 2/15/2018), but I could see this getting cumbersome...

For example, I could see:
"Your application for %SCHOOL% is due on %APPLICATION_DATE%" turning into:
"Your application for Temple, Drexel, and Penn is due on 2/1/2018, 2/7/2018, and 2/15/2018"

...being really clumsy (doesn't quite make grammatical sense in this example).

Any thoughts on how we should handle this?

**Comment by michiQ** [comment]
I think we are actually ok here because application submission date is only one reminder and it only shows up 1day before submission.  So if we are de duping by date there's only one date on that reminder. Seems to show up correctly. Course I'm old and it's late so I might not be thinking clearly. 😝

**Comment by bobderrico80** [comment]
Ah yes, you are right. They would be the same date anyway. This would break on "absolute" timeframes (like NCDD), but it wouldn't make sense to put an application due date on that page anyway.
