### ISSUE TITLE
Create a help button and modal

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#183]
This is one create a help icon with a pop up when people have problems and want to communicate to us about the bug

**Comment by bobderrico80** [comment]
We probably also want to add it to the "Uh oh" dialog.

**Comment by michiQ** [comment]
![lightbub.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5820d7b9c83da81300226c3e/125516c66e82c728ace21e0d46e49d9d2b9681bc8dabf301b44fff9e2c4533317346f67d26d2ba79e7472d005e0b47f8455e5f44aefadb28a2b62e6c981e5ab38532022d8c6853beb2901db90bbb24824684b1bb894ec3ee3b27f5c6.PNG)

**Comment by michiQ** [comment]
prototype https://preview.uxpin.com/d12ebc3eaee7168ca3fa15eddc0ef90df9357b3e
