### ISSUE TITLE
Database migration - API - SQL- Account

### ISSUE THREAD

**Issue by adobley** [yadaguru/yadaguru-app#33]
A migration to a relational database was suggested. The main idea was to get the joins out of code, especially getting them out of the frontend would improve application performance on mobile.

If we want to stick with a document DB the option there is RethinkDB. This offers support for joins and a number of other features. This would currently limit our ability to build for Windows, since windows does not have a version for Rethink at this time. I know there is a Windows version in the works and is in no way a killer for us.

I think that jumping over to Postgresql would be a wise decision. It has the relational model which will help with our document structure and will make the user management far easier if we begin to go that route.

I'd love to hear others thoughts, suggestions, criticisms, ect.

**Comment by bobderrico80** [comment]
Moving to yadaguru-api issues
