### ISSUE TITLE
Cleaner Date Selection

### ISSUE THREAD

**Issue by adobley** [yadaguru/yadaguru-app#34]
The order of the pills could be better defined. Something such as adding lines or arrows to direct the users eye to what is next. We cannot assume that all users will read left to right, row by row. As we saw some users went top to bottom for each item.

Something like below would be an option.
![image](https://cloud.githubusercontent.com/assets/9088981/10366817/ec67c862-6d9a-11e5-8cf2-3f3c67dc48ad.png)

**Comment by michiQ** [comment]
new ux incorporates this selection https://live.uxpin.com/288d7fede09c9a3618e31be42b3e10a7de6cbdfd#/pages/30689783

First level is 
To Do By

Second level will show the Reminder Title (ie Ask for Teacher Recommendations').

When the user clicks on the second level, then they will see all the details.

**Comment by michiQ** [comment]
closed as the ux now gives the wireframe for how this is to be done and Bob is working on the front end.
