### ISSUE TITLE
To Server or not to Server

### ISSUE THREAD

**Issue by adobley** [yadaguru/yadaguru-app#36]
This is a big one. We need to decide are we going to continue going forward with the idea that we will ultimately be serving all of our assets through CDN with the server only hosting a html page through nginx or similar? Or, are we going to persist user data and build in more server side features such as support for email, ect?

This effects the work I've been doing on dev tooling, the process for the build for releases, and more.

If we are limiting ourselves to the html page and resources that can be CDN'd it limits the scope of our abilities, but also greatly limits the cost and with no backend scalability isn't even an issue.

If we are going to move forward and build in the more advanced features, such as emails and SMS, it is likely that we will need more backend work.

What we can do is have the static resources served via CDN/nginx or similar and have an API only on the node.js/elixir/python/whatever we decide on. If we go this way we should likely split the app into this repo(app) and another repo(api).

Those are my thoughts right now. This is another discussion post so go nuts with ideas, criticisms, ect.

**Comment by titlecharacter** [comment]
Pretty much everyone I've discussed this with - including some teachers - has either assumed or suggested, unprompted, that it uses notifications/emails/texts/etc to push reminders at students. 

Inasmuch as cost/scaling is a concern: In the near term, Code for Philly has AWS hosting resources we're very happy to direct toward this project if necessary. If it goes beyond that, we can go find the funding to support it. "We have too many students using this service" is a really great problem to have, and Code for Philly has your back both for short-term needs and longer-term fundraising (if necessary.)

**Comment by adobley** [comment]
Sounds good. I really appreciate the support of CfP. I know this was a discussion earlier in the project history so I wanted to make sure it wasn't forgotten.

With the support of more AWS resources it is much less to worry about. I'm going to close this for the time being.
