### ISSUE TITLE
Guided Reminder Process

### ISSUE THREAD

**Issue by adobley** [yadaguru/yadaguru-app#37]
The process for getting reminders needs to be improved.

The current floating suggestion is to remove the fields that are seen and make the process guided. An example of the process would be:
- Click Get Reminders
- Prompted for school name
- Prompted for date

Based on users interactions in demos this would improve the interaction and reduce on screen usage.

**Comment by michiQ** [comment]
new UX now has guided reminder process when users press the ? button.  Help adjusts based on which page you're on. Guided first use process is on the home  page. https://live.uxpin.com/288d7fede09c9a3618e31be42b3e10a7de6cbdfd#/pages/30689783
