### ISSUE TITLE
Push to SMS/Twilio Development

### ISSUE THREAD

**Issue by adobley** [yadaguru/yadaguru-app#38]
Push to SMS is the killer feature that is needed for the school district to be behind us.

There are a couple things that need to be decided on:

First, what service are we going to use for our SMS, for at least our development process? We do not need to lock into a service for the life of the project, but we need to pick our initial service provider is necessary.

With regards to business logic, how do we want to schedule the alerts? 
My suggestion would be that we set a default, which can be overridden if its set on the category, which can further be overridden if it is set for a specific reminder. This way we have granular control when we need it but still have a default to fall back onto. We can use a similar setting to decide what, if any, alerts we repeat.

If we decide to support user accounts we can allow the users to set the timing for their alerts if they choose to customize them.

**Comment by titlecharacter** [comment]
I know @timwis has some experience in this and in the past Twilio's reached out to us for promotion.

**Comment by timwis** [comment]
I've used twilio and it's very easy to get up and running. They launched twilio.org for non profits and they'd probably throw free credits at a code for philly project. Brent from twilio comes to code for philly from time to time.

**Comment by michiQ** [comment]
We'll probably need a 'Hello...welcome to YadaGuru' text with instructions on how to turn off the texting service.

**Comment by bobderrico80** [comment]
I think Twilio would be ideal and is much preferred to the "email to SMS" method. Glad to know that they might be able to help us out as a non profit.

**Comment by michiQ** [comment]
Need the first message to be a yes confirmation from the user. This is becuase users can sign up other phones for text messages.  This would be if we used either twilio or email sms.

**Comment by bobderrico80** [comment]
This issue was moved to yadaguru/yadaguru-api#9
