### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by adobley** [yadaguru/yadaguru-app#39]
Part of this overall issue is addressed in #34, but this is for discussion on improvements that can be made. Mobile UX is a big part of this, since most users are anticipated to be hitting on mobile.

One suggestion has been floated that we collapse the buttons after a reminder is chosen. So we would list only:
- SMS Reminders
- Export 
- Restart

Export would break out display of exporting to PDF, print, ical, google calendar, and any other export actions we develop.

Smaller suggestions currently:
- Autoscroll the browser to the date selection nav
- Add date selection nav mirrored on the bottom of the reminders selected
- Support swiping left/right to go forward/backward through reminder selection.

These can be broken out into enhancement issues if we decide its worth pursuing right now. Priority is still MVP, but if anyone is open to work on these problems it would be appreciated.

**Comment by michiQ** [comment]
design concept 
![image](https://cloud.githubusercontent.com/assets/8203279/10397335/2529ca30-6e75-11e5-89ff-69a32d0e4a61.png)

Button Order:
Check Icon - Reminders
SMS Icon - Push to SMS
Save Icon - Save to PDF
Calendar Icon - Push to Ical/google cal
Also need a button to restart - which would send you back to the front page
check out the current app on mobile for reference http://www.yadaguru.com

**Comment by donutage** [comment]
Another suggestion would be reducing the vertical size of the Yadaguru logo in the mobile layout. Right now, it takes up almost half the screen on my phone. Maybe more like a scaled-down version of the 'wide' logo?

**Comment by lmdiby** [comment]
New UX design incorporating comments from this and other issues https://live.uxpin.com/5ea7b17b80e991d0d88af5014a3489f5c257c94c#/pages/30326244

**Comment by michiQ** [comment]
Latest UX Version https://live.uxpin.com/288d7fede09c9a3618e31be42b3e10a7de6cbdfd#/pages/30689783
