### ISSUE TITLE
Multi-school Support

### ISSUE THREAD

**Issue by adobley** [yadaguru/yadaguru-app#41]
Some reminders are duplicated unnecessarily when getting reminders for multiple colleges. Such as SAT's or asking for recommendations, these activities could be completed at one time for multiple colleges.

We need to look at how we can adjust the design to better support this. This becomes much easier if we support an account system in some ways as we can keep track and colleges can be added or removed over time.

At a minimum my initial thought is that we could support selecting multiple schools when getting reminders. Then each reminder would need to be clearly marked if it is a global reminder or for a specific school.

I'm hoping some better ideas than mine can surface.

**Comment by michiQ** [comment]
how bout a boolen yes/no on the testing reminders.  We'll have the phone number to identify.  So the logic might be, is this a first time user yes/no.  if yes, then don't send the testing reminders?

**Comment by adobley** [comment]
Would there ever be an edge case where a test would need to be done earlier?

For example: a student has a due day in spring but then now adds a school with rolling admissions starting in winter. Wouldn't the testing need to be done earlier?

Maybe we could check against the phone # and if the new suggested test date is earlier, use that one instead.

**Comment by michiQ** [comment]
The test dates are generic, meaning we send all of them starting from the date that the student runs the 'get my reminders'.  So if the date was 1/1/2016 or 4/1/2016 we send them all the test dates starting from the day they clicked 'get my reminders'.  So its really the date they run the app that would tell us which testing reminders to send.  The yes/no only prevents us from sending them, in this case, two reminders about the same test date.

**Comment by adobley** [comment]
Okay, that is simpler than I initially expected. Thanks for the input. Its not my domain so that's what I ask.

Are there any reminders that we would want to watch out for duplication on? Recommendations, other supplementary materials they could request all at once instead of once for each college?

Its not a priority, I'm just curious if there's a way we can reduce the "noise" in the reminders. If this is not-an-issue I can just close it for now.

**Comment by michiQ** [comment]
I think the Fafsa Reminder and the NCDD Date (national college decision day)
