### ISSUE TITLE
Text cost prediction

### ISSUE THREAD

**Issue by titlecharacter** [yadaguru/yadaguru-app#47]
Twilio will provide info on how many texts YadaGuru has sent, but it'll be important to be able to monitor expected costs, not just those already incurred. Knowing the number of students subscribed, how many schools they're applying to, etc, it's possible to project how many text messages will be sent out in total for current users, and therefore what the expected cost is.

**Comment by michiQ** [comment]
agreed.  I'm envisioing a combination of google analytics monitoring and a spreadsheet with numbers already plugged in.  Got the analytics, how can I find out about the twilio pricing model to plug into the spreadsheet? I understand there's an inital lower cost or free tier and then does it go up to the normal rate or would we still be at a reduced rate?  Thanks - with that info I should have a sheet prepped in the next week or two.

**Comment by titlecharacter** [comment]
http://www.twilio.org/ - Nonprofits get a $500 starter bucket and a 25% discount off.
https://www.twilio.com/sms/pricing pricing is here.

Will that spreadsheet auto-adjust if you add/subtract things from the cadence? I was actually envisioning code that would run periodically and calculate it based on exactly what all users are getting (ie, as the cadence gets more complex/customized it adapts) but I'm also prone to looking to code for things where a spreadsheet will get 95% of the way there for much less effort :-)

**Comment by michiQ** [comment]
well - it will take a human to put in the starter number.  I'm thinking something like 

((average number of direct users in a week (this is the part that a human would add through a google analytics review)) 
X (4(average number of schools)) 
X (30 (average number of text messages per school))

=subtotal: average number of texts a week

X Twillio cost model

**Comment by michiQ** [comment]
Test cost spreadsheet created and posted to slack
