### ISSUE TITLE
Privacy policy?

### ISSUE THREAD

**Issue by titlecharacter** [yadaguru/yadaguru-app#48]
Probably goes here rather than in an email thread:

YG is collecting personal information from minors, so a good privacy policy is going to be important. Should make sure it's clear about what won't be passed on/sold but allows for anonymized aggregated public stats, so you're not inhibited from, eg, promoting the app by talking about percentage of users who applied to local universities with it, or high schools that participate.

@AcriCAA suggested this as a starting point:

https://www.slideshare.net/DrexelELC/protect-privacy-to-protect-your-startup?from_m_app=ios

**Comment by michiQ** [comment]
Will do.  Looking for a privacy policy now.  From what I'm reading we are pretty light.  We collect only mobile number.  That number is associated with public data about schools and school submission dates.  I think only the mobile number has to be protected.  I've added a 'forget my number' check box to a new reminder admin page to allow for the Forget Me provisions.   Not sure if we have cookies and/or if google analytics is dropping cookies so need to figure that one out.

**Comment by AcriCAA** [comment]
@imdiby Just to be clear the link @bennovack provided above is a slideshow about privacy concerns. It contains links to privacy policy generators which you should look into: 

http://www.freeprivacypolicy.com/index-oct2015.php?utm_expid=87121688-74.enw4odzTR2a9UupCh5ATsg.1

I recommend looking at [this one from TrustE](https://www.truste.com/business-products/dpm-platform/)

**Comment by michiQ** [comment]
Privacy policy has been created and linked to the current site through the FAQ page.
