### ISSUE TITLE
Develop new front end based on new UX

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#49]
Here is the Returning user flow https://live.uxpin.com/288d7fede09c9a3618e31be42b3e10a7de6cbdfd#/pages/30689789 

Here is the new user flow
https://live.uxpin.com/9b4ba59f29ab83a34a5d98f606f4696aab330b21#/pages/31898600

Best to look at both from your mobile.

**Comment by michiQ** [comment]
Bob is currently working on this and should be consulted before starting work. @bobderrico80

**Comment by bobderrico80** [comment]
This has been broken into sub-issues. Closing.
