### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by bobderrico80** [yadaguru/yadaguru-app#81]
Currently, there is no mechanism for error-handling. If a request to the API fails, it will fail silently. At a minimum, we need to pop a modal letting the user know that there is a problem. 

We will need to add this to the failure callback to http calls.

**Comment by bobderrico80** [comment]
@lmdiby curious to your thoughts on this from a UI/UX perspective

**Comment by bobderrico80** [comment]
With the recent API udpates, a handleHttpError (in the errorService) will be called on all AJAX failure callbacks. Currently, this will just log the error to the console. 

This should be refactored so that users are presented with a notice of the failure (modal, flash, etc.), with a next step (contacting us, trying again, etc.)

**Comment by bobderrico80** [comment]
See #103 for specific UI mockups and flow for handling an incorrect confirmation code

**Comment by michiQ** [comment]
Bob - how's this? 
![screen shot 2016-11-11 at 11 13 32 am](https://cloud.githubusercontent.com/assets/8203279/20221631/0e4f8a00-a800-11e6-8e2b-b0521d75e76b.png)

the button could be a refresh of the app?
