### ISSUE TITLE
AWS Think

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-app#98]

**Comment by michiQ** [comment]
This issue is around thinking about how/when we'll move to the CFP instance of AWS.  We'll wait for the prototype to be done and then get with CFP on it.  I'll take it and set up the meet probably in late December.

**Comment by bobderrico80** [comment]
Also to consider...  which AWS services/configurations are appropriate for the current app architecture, and how will we run deployments.

**Comment by bobderrico80** [comment]
Documenting the current app architecture, as well as some initial thoughts on which AWS services to use (I am by no means an AWS expert, so we'll definitely need some input on this)
- A NodeJS application that provides a REST api for app data (EC2 instance(s)?)
- A postgresql database (RDS?)
- An angular app for the front-end (all static assets, can we just serve from an S3 bucket)?
- An angular app for the admin interface (S3?)
- A service for sending daily SMS messages (another EC2 instance, or maybe a good candidate for Lambda?)

**Comment by michiQ** [comment]
closing this based on convo had at CFP about migrating to cfp AWS.  We are going to do this, but later - after dockerise and finishing up the app.
